version: "3.9"

services:

  database:
    image: mysql
    container_name: bd
    environment:
      MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_PASSWORD: 'password'
      MYSQL_DATABASE: 'banco'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
    driver: local

    